### ISSUE TITLE
NoReverseMatch: 'admin' is not a registered namespace

### ISSUE THREAD

**Issue by evildmp** [romlok/django-form-designer#3]
After adding:

```
    urlpatterns = patterns('',
        (r'^forms/', include('form_designer.urls')),
        ...
    )
```

to `urls.py`, any attempt to visit an admin URL produces a traceback like http://dpaste.com/1035621/

**Comment by romlok** [comment]
Certainly could be a confusing problem for people new to Django. Good job noticing and patching the instructions.
